# -*- coding: utf-8 -*-
"""day2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilriJSzlKBGPJBTVzzw9bj-b3B2-7kr5
"""

liste=[40,50,60,70]
liste[0],liste[2]=liste[2],liste[0]
liste[1],liste[3]=liste[3],liste[1]
print(liste)

n=int(input("n değerini giriniz:"))
for i in range(0,n+1):
  print(i,end=" ")