# -*- coding: utf-8 -*-
"""day2.py

Automatically generated by Colaboratory.
1.

liste=[40,50,60,70]
liste[0],liste[2]=liste[2],liste[0]
liste[1],liste[3]=liste[3],liste[1]
print(liste)

2.

n=int(input("n değerini giriniz:"))
for i in range(0,n+1):
  print(i,end=" ")
