# -*- coding: utf-8 -*-
"""day4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilriJSzlKBGPJBTVzzw9bj-b3B2-7kr5
"""

print("***COURSE GRADE APPLICATION***")
print("Birinci öğrencinin notlarını giriniz.")
vizeNotu=int(input("Vize notunu giriniz:"))
finalNotu=int(input("Final notunu giriniz:"))
projeNotu=int(input("Proje notunu giriniz:"))
gecmeNotu1=((vizeNotu*0.3)+(projeNotu*0.3)+(finalNotu*0.4))

print("İkinci öğrencinin notlarını giriniz.")
vizeNotu=int(input("Vize notunu giriniz:"))
finalNotu=int(input("Final notunu giriniz:"))
projeNotu=int(input("Proje notunu giriniz:"))
gecmeNotu2=((vizeNotu*0.3)+(projeNotu*0.3)+(finalNotu*0.4))

print("Üçüncü öğrencinin notlarını giriniz.")
vizeNotu=int(input("Vize notunu giriniz:"))
finalNotu=int(input("Final notunu giriniz:"))
projeNotu=int(input("Proje notunu giriniz:"))
gecmeNotu3=((vizeNotu*0.3)+(projeNotu*0.3)+(finalNotu*0.4))

print("Dördüncü öğrencinin notlarını giriniz.")
vizeNotu=int(input("Vize notunu giriniz:"))
finalNotu=int(input("Final notunu giriniz:"))
projeNotu=int(input("Proje notunu giriniz:"))
gecmeNotu4=((vizeNotu*0.3)+(projeNotu*0.3)+(finalNotu*0.4))

print("Beşinci öğrencinin notlarını giriniz.")

vizeNotu=int(input("Vize notunu giriniz:"))
finalNotu=int(input("Final notunu giriniz:"))
projeNotu=int(input("Proje notunu giriniz:"))
gecmeNotu5=((vizeNotu*0.3)+(projeNotu*0.3)+(finalNotu*0.4))

students_information={
    "ogrenci1":gecmeNotu1,
    "ogrenci2":gecmeNotu2,
    "ogrenci3":gecmeNotu3,
    "ogrenci4":gecmeNotu4,
    "ogrenci5":gecmeNotu51,
}
index1=list(students_information.values())
yeni_index1=sorted(index1,reverse=True)
print(yeni_index1)